Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
Exception on /api/settings [POST]
Traceback (most recent call last):
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikevanis/Naturewatch/NaturewatchCameraServer/naturewatch_camera_server/api.py", line 84, in settings_handler
    if "mode" in settings["exposure"]:
KeyError: 'exposure'
